package com.instrumentalsw.backend.domain;

public enum UploadErrorCode {
    AUDIO_FILE_REQUIRED,
    EMPTY_AUDIO_FILE,
    UNSUPPORTED_AUDIO_FORMAT,
    INVALID_SAXOPHONE_TYPE,
    INVALID_INPUT_MODE,
    AUDIO_SIZE_LIMIT_EXCEEDED,
    INVALID_TRANSCRIPTION_REQUEST,
    INVALID_JOB_ID,
    TRANSCRIPTION_NOT_FOUND,
    AI_SERVICE_UNAVAILABLE,
    AI_SERVICE_ERROR
}
