package com.instrumentalsw.backend.domain;

public enum UploadErrorCode {
    AUDIO_FILE_REQUIRED,
    EMPTY_AUDIO_FILE,
    UNSUPPORTED_AUDIO_FORMAT,
    INVALID_SAXOPHONE_TYPE,
    INVALID_INPUT_MODE,
    AUDIO_SIZE_LIMIT_EXCEEDED,
    INVALID_TRANSCRIPTION_REQUEST,
    INVALID_JOB_ID,
    TRANSCRIPTION_NOT_FOUND,
    TRANSCRIPTION_RESULT_NOT_READY,
    REVISION_NOT_FOUND,
    REVISION_CONFLICT,
    INVALID_REVISION_OPERATION,
    INVALID_REVISION_EVENT,
    AI_SERVICE_UNAVAILABLE,
    AI_SERVICE_ERROR
}
